services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: safe_voice_db
      DB_USERNAME: safevoice_user
      DB_PASSWORD: safevoice_pass
    depends_on:
      - postgres
    networks:
      - safevoice-network

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: safe_voice_db
      POSTGRES_USER: safevoice_user
      POSTGRES_PASSWORD: safevoice_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safevoice-network

networks:
  safevoice-network:
    driver: bridge

volumes:
  postgres_data: